## Numpy

In [16]:
import numpy as np
arr = np.array([1,2,3,4])

In [17]:
print(arr)

[1 2 3 4]


In [18]:
print(type(arr))

<class 'numpy.ndarray'>


## Creating python list using range

In [19]:
size = 10

py_list = list(range(size))

print(py_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Numpy vs List

1. NumPy arrays are faster (optimized in C)
2. NumPy stores data in continuous memory blocks
3. Uses less memory (optimized storage)
4. Built-in mathemetical functions
5. Supports direct vectorized operations

In [20]:
import time

# list
size = 1_000_000
py_list = list(range(size))
start_time = time.time()
sq_list = [x ** 2 for x in py_list]
end_time = time.time()
print(f"List calculation time = {end_time - start_time}")

# numpy

size = 1_000_000
np_array = np.array(py_list)
start = time.time()
sq_list = np_array ** 2 
end = time.time()
print(f"numpy calculation time = {end - start}")

List calculation time = 0.1814274787902832
numpy calculation time = 0.018004894256591797


In [21]:
import sys

print(f"memory occupied by python list = {sys.getsizeof(py_list) *len(py_list)} bytes")
print(f"memory occupied by numpy = {np_array.nbytes} bytes")

memory occupied by python list = 8000056000000 bytes
memory occupied by numpy = 8000000 bytes


## So why is Numpy faster?
- Homogeneous Data Types and Contiguous Memory
- Vector Operations & C Implementations
- Reduced Overhead

### homogeneous nature of numpy
Note: 
- <U21 means string stored
- int64 means integer

In [22]:
arr = np.array([1, 2, 3, 4, 5])
print("array = " ,arr)
print("type = ", type(arr) )
print("data type = " , arr.dtype )
print("Shape = " ,arr.shape) # rows, column
print("dimension = " , arr.ndim)

print("\nhomoneneous\n")

arr1 = np.array([1, 2, 3, 4, 5, "hello"]) # all become string type
print("array = " ,arr1)
print("type = ", type(arr1) )
print("data type = " , arr1.dtype )
print("Shape = " ,arr1.shape) # rows, column
print("dimension = " , arr1.ndim)

array =  [1 2 3 4 5]
type =  <class 'numpy.ndarray'>
data type =  int64
Shape =  (5,)
dimension =  1

homoneneous

array =  ['1' '2' '3' '4' '5' 'hello']
type =  <class 'numpy.ndarray'>
data type =  <U21
Shape =  (6,)
dimension =  1


### 2d array

In [23]:
arr2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 3, 4],
    [4, 2, 1]
])
print("array = " ,arr2D)
print("type = ", type(arr2D) )
print("data type = " , arr2D.dtype )
print("Shape = " ,arr2D.shape) # rows, column
print("dimension = " , arr2D.ndim)

array =  [[1 2 3]
 [4 5 6]
 [2 3 4]
 [4 2 1]]
type =  <class 'numpy.ndarray'>
data type =  int64
Shape =  (4, 3)
dimension =  2


## creating numpy arrays from skretch

In [24]:
# assigning all values to zero
array1 = np.zeros((2,3), dtype= "int64")
print(array1, array1.shape, array1.dtype)

[[0 0 0]
 [0 0 0]] (2, 3) int64


In [25]:
# without datatype it becomes float
array2 = np.ones((3,4))
print(array2, array2.shape, array2.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4) float64


In [26]:
# assiging desired value
array3 = np.full((3,5), 100)
print(array3, array3.shape, array3.dtype)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]] (3, 5) int64


In [27]:
array4 = np.eye(3)
print(array4, array4.shape, array4.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) float64


In [28]:
arr5 = np.arange(8,)
print(arr5)

[0 1 2 3 4 5 6 7]


In [29]:
arr6 = np.arange(0, 11, 2)
print(arr6)

[ 0  2  4  6  8 10]


In [30]:
arr7 = np.linspace(1, 100, 5)
print(arr7)

[  1.    25.75  50.5   75.25 100.  ]


In [31]:
arr8 = np.arange(1,11)
print(arr8)
print("size = " , arr8.size)
print("data type = ", arr8.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
size =  10
data type =  int64


In [32]:
#typeConversion in numpy
float_arr = arr8.astype(np.float64)
print(float_arr)
print("data_type = ", float_arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
data_type =  float64


# Operation on numpy arrray

In [33]:
array3 = np.array([[1, 2, 3], [5, 4, 3]])
print(array3, array3.shape)

[[1 2 3]
 [5 4 3]] (2, 3)


In [34]:
reshaped = array3.reshape(3,2)
print(reshaped, array3.shape)

[[1 2]
 [3 5]
 [4 3]] (2, 3)


In [35]:
flattened = array3.flatten()
print(flattened)

[1 2 3 5 4 3]


## Indexing

In [36]:
arr = np.array([1, 2, 3, 5, 4, 3])
print(arr[0])
print(arr[1])

1
2


|   | 0 | 1 | 2 |
|---|---|---|---|
| 0 | 1 | 2 | 3 |
| 1 | 5 | 4 | 3 |

In [37]:
arr = np.array([[1, 2, 3], [5, 4, 3]])
print(arr[1][1])
print(arr[1][0])
print(arr[0][1])

4
5
2


## fancy indexing

In [38]:
arr = np.array([1, 2, 3, 5, 4, 3])
idx = [0, 1, 3]
print(arr[idx]) # accesssing multiple idx

[1 2 5]


## Boolean indexing

In [39]:
arr = np.array([1, 2, 3, 5, 4, 3])

print(arr[arr>2]) # all ele greater than 2
print(arr[arr % 2 ==0]) # we get all even values

[3 5 4 3]
[2 4]


## slicing

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[::]) # get all element
print(arr[1:4]) # idx 1 is included while idx 4 is excluded
print(arr[1:])
print(arr[::2]) # last index is step

[1 2 3 4 5 6]
[2 3 4]
[2 3 4 5 6]
[1 3 5]


## Copy and view
- In list slicing create a new copy in another memory location
- numpy creates only view

In [41]:
# list
print("\n list\n")
nums = ([1, 2, 3, 4, 5, 6])
sub_list = nums[1:3]  # new memory location
print("sublist after slicing :", sub_list)

sub_list[0] = 200
print("updated sublist :", sub_list)
print("original :", nums) # oiginal remains same


print("\n numpy\n")
# numpy
num = np.array([1, 2, 3, 4, 5, 6])
sub_lists = num[1:3]
print("sublist after slicing :",sub_lists)

sub_lists[0] = 200
print("updated sublist :", sub_lists)
print("original :",num)


 list

sublist after slicing : [2, 3]
updated sublist : [200, 3]
original : [1, 2, 3, 4, 5, 6]

 numpy

sublist after slicing : [2 3]
updated sublist : [200   3]
original : [  1 200   3   4   5   6]


## Data type in numpy

In [42]:
data = np.array([1, 2, 3, "hello ji"])
print(data.dtype)

<U21


In [43]:
data = np.array([1, 2, 3, 8.76])
print(data.dtype)

float64


In [44]:
data = np.array([1, 2, 3])
print(data.dtype)

int64


In [45]:
data = np.array([1, 2, 3, 3+5j])
print(data.dtype)

complex128


In [46]:
#complex

compx1 = 3+7j
compx2 = 6+4j

print("sum",compx1+compx2 )

sum (9+11j)


In [47]:
# object
data = np.array([1, 2, 3, 3+5j, {"a", "s"}, 8.7])
print(data.dtype)

object


## Axis in Multidimensional Array

In [48]:
import numpy as np
arr2D = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
print(np.sum(arr2D))

45


In [50]:
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

[12 15 18]


In [51]:
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print("\n")
print(arr2D[0:2, 1:2])

[ 6 15 24]


[[2]
 [5]]


### 3D Array

In [52]:
arr3D = np.array([[[1, 2], [3,4],[5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3D, arr3D.shape)

print(".......................")

#indexing
print(arr3D[1, 1, 0])

# slicing
arr3D[:, 0, :] = 99 # first row from both layers
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
.......................
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


## Vectorization and Broadcasting

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr**2)
print(arr+10)

[ 1  4  9 16 25]
[11 12 13 14 15]
